// Generated from https://github.com/ehn-dcc-development/ehn-dcc-schema => valuesets/country-2-codes.json
import Foundation
public enum CountryCode: String {
	case unknown = "unknown"
	case country_mv = "MV"
	case country_ve = "VE"
	case country_to = "TO"
	case country_by = "BY"
	case country_ck = "CK"
	case country_ms = "MS"
	case country_sy = "SY"
	case country_bj = "BJ"
	case country_bq = "BQ"
	case country_tz = "TZ"
	case country_cx = "CX"
	case country_my = "MY"
	case country_je = "JE"
	case country_dz = "DZ"
	case country_ua = "UA"
	case country_om = "OM"
	case country_tj = "TJ"
	case country_mf = "MF"
	case country_mc = "MC"
	case country_hm = "HM"
	case country_ie = "IE"
	case country_bz = "BZ"
	case country_ye = "YE"
	case country_ad = "AD"
	case country_ne = "NE"
	case country_cl = "CL"
	case country_gm = "GM"
	case country_cw = "CW"
	case country_sn = "SN"
	case country_gn = "GN"
	case country_eh = "EH"
	case country_zm = "ZM"
	case country_af = "AF"
	case country_zw = "ZW"
	case country_cr = "CR"
	case country_vi = "VI"
	case country_ag = "AG"
	case country_rs = "RS"
	case country_al = "AL"
	case country_me = "ME"
	case country_bs = "BS"
	case country_ch = "CH"
	case country_mp = "MP"
	case country_mm = "MM"
	case country_sb = "SB"
	case country_bd = "BD"
	case country_gi = "GI"
	case country_mo = "MO"
	case country_fj = "FJ"
	case country_mw = "MW"
	case country_sx = "SX"
	case country_so = "SO"
	case country_hk = "HK"
	case country_sa = "SA"
	case country_no = "NO"
	case country_ni = "NI"
	case country_sg = "SG"
	case country_tr = "TR"
	case country_ax = "AX"
	case country_pg = "PG"
	case country_dm = "DM"
	case country_tt = "TT"
	case country_am = "AM"
	case country_dj = "DJ"
	case country_tv = "TV"
	case country_pt = "PT"
	case country_cu = "CU"
	case country_aq = "AQ"
	case country_gr = "GR"
	case country_gw = "GW"
	case country_wf = "WF"
	case country_tc = "TC"
	case country_sr = "SR"
	case country_gl = "GL"
	case country_aw = "AW"
	case country_lu = "LU"
	case country_ru = "RU"
	case country_kw = "KW"
	case country_bl = "BL"
	case country_bt = "BT"
	case country_mz = "MZ"
	case country_pe = "PE"
	case country_pn = "PN"
	case country_cv = "CV"
	case country_sk = "SK"
	case country_nu = "NU"
	case country_at = "AT"
	case country_it = "IT"
	case country_az = "AZ"
	case country_uy = "UY"
	case country_gu = "GU"
	case country_sh = "SH"
	case country_ht = "HT"
	case country_ph = "PH"
	case country_lb = "LB"
	case country_va = "VA"
	case country_si = "SI"
	case country_br = "BR"
	case country_mn = "MN"
	case country_kr = "KR"
	case country_hr = "HR"
	case country_fi = "FI"
	case country_ga = "GA"
	case country_lt = "LT"
	case country_yt = "YT"
	case country_lv = "LV"
	case country_ma = "MA"
	case country_kp = "KP"
	case country_er = "ER"
	case country_ps = "PS"
	case country_pk = "PK"
	case country_ly = "LY"
	case country_pa = "PA"
	case country_kz = "KZ"
	case country_hn = "HN"
	case country_as = "AS"
	case country_fr = "FR"
	case country_mr = "MR"
	case country_mx = "MX"
	case country_sm = "SM"
	case country_cz = "CZ"
	case country_nl = "NL"
	case country_za = "ZA"
	case country_ec = "EC"
	case country_tw = "TW"
	case country_tl = "TL"
	case country_mk = "MK"
	case country_fm = "FM"
	case country_lc = "LC"
	case country_la = "LA"
	case country_ls = "LS"
	case country_hu = "HU"
	case country_gh = "GH"
	case country_lk = "LK"
	case country_tf = "TF"
	case country_tk = "TK"
	case country_pf = "PF"
	case country_ir = "IR"
	case country_li = "LI"
	case country_bi = "BI"
	case country_gq = "GQ"
	case country_iq = "IQ"
	case country_ml = "ML"
	case country_ky = "KY"
	case country_ss = "SS"
	case country_tg = "TG"
	case country_cd = "CD"
	case country_io = "IO"
	case country_bn = "BN"
	case country_gy = "GY"
	case country_bb = "BB"
	case country_ke = "KE"
	case country_nr = "NR"
	case country_sc = "SC"
	case country_um = "UM"
	case country_et = "ET"
	case country_bv = "BV"
	case country_fo = "FO"
	case country_es = "ES"
	case country_mq = "MQ"
	case country_ai = "AI"
	case country_nf = "NF"
	case country_sd = "SD"
	case country_tn = "TN"
	case country_in = "IN"
	case country_st = "ST"
	case country_na = "NA"
	case country_cm = "CM"
	case country_jm = "JM"
	case country_ba = "BA"
	case country_sl = "SL"
	case country_gd = "GD"
	case country_fk = "FK"
	case country_do = "DO"
	case country_ci = "CI"
	case country_bh = "BH"
	case country_dk = "DK"
	case country_kg = "KG"
	case country_pm = "PM"
	case country_mh = "MH"
	case country_bf = "BF"
	case country_pl = "PL"
	case country_uz = "UZ"
	case country_gb = "GB"
	case country_bo = "BO"
	case country_ar = "AR"
	case country_id = "ID"
	case country_lr = "LR"
	case country_gs = "GS"
	case country_mu = "MU"
	case country_ug = "UG"
	case country_kh = "KH"
	case country_ro = "RO"
	case country_ws = "WS"
	case country_vu = "VU"
	case country_bm = "BM"
	case country_is = "IS"
	case country_vc = "VC"
	case country_gp = "GP"
	case country_td = "TD"
	case country_eg = "EG"
	case country_mg = "MG"
	case country_md = "MD"
	case country_vg = "VG"
	case country_de = "DE"
	case country_pr = "PR"
	case country_ae = "AE"
	case country_jo = "JO"
	case country_cc = "CC"
	case country_sv = "SV"
	case country_sz = "SZ"
	case country_th = "TH"
	case country_ki = "KI"
	case country_gg = "GG"
	case country_nc = "NC"
	case country_au = "AU"
	case country_ca = "CA"
	case country_im = "IM"
	case country_tm = "TM"
	case country_rw = "RW"
	case country_bg = "BG"
	case country_cn = "CN"
	case country_gt = "GT"
	case country_py = "PY"
	case country_vn = "VN"
	case country_co = "CO"
	case country_ee = "EE"
	case country_pw = "PW"
	case country_re = "RE"
	case country_sj = "SJ"
	case country_ao = "AO"
	case country_cf = "CF"
	case country_cg = "CG"
	case country_nz = "NZ"
	case country_qa = "QA"
	case country_be = "BE"
	case country_us = "US"
	case country_jp = "JP"
	case country_mt = "MT"
	case country_ge = "GE"
	case country_gf = "GF"
	case country_km = "KM"
	case country_ng = "NG"
	case country_se = "SE"
	case country_np = "NP"
	case country_kn = "KN"
	case country_il = "IL"
	case country_bw = "BW"
	case country_cy = "CY"
	var display: String {
		switch self {
		case .unknown: return "unknown"
		case .country_mv: return "Maldives"
		case .country_ve: return "Venezuela, Bolivarian Republic of"
		case .country_to: return "Tonga"
		case .country_by: return "Belarus"
		case .country_ck: return "Cook Islands"
		case .country_ms: return "Montserrat"
		case .country_sy: return "Syrian Arab Republic"
		case .country_bj: return "Benin"
		case .country_bq: return "Bonaire, Sint Eustatius and Saba"
		case .country_tz: return "Tanzania, United Republic of"
		case .country_cx: return "Christmas Island"
		case .country_my: return "Malaysia"
		case .country_je: return "Jersey"
		case .country_dz: return "Algeria"
		case .country_ua: return "Ukraine"
		case .country_om: return "Oman"
		case .country_tj: return "Tajikistan"
		case .country_mf: return "Saint Martin (French part)"
		case .country_mc: return "Monaco"
		case .country_hm: return "Heard Island and McDonald Islands"
		case .country_ie: return "Ireland"
		case .country_bz: return "Belize"
		case .country_ye: return "Yemen"
		case .country_ad: return "Andorra"
		case .country_ne: return "Niger"
		case .country_cl: return "Chile"
		case .country_gm: return "Gambia"
		case .country_cw: return "Curaçao"
		case .country_sn: return "Senegal"
		case .country_gn: return "Guinea"
		case .country_eh: return "Western Sahara"
		case .country_zm: return "Zambia"
		case .country_af: return "Afghanistan"
		case .country_zw: return "Zimbabwe"
		case .country_cr: return "Costa Rica"
		case .country_vi: return "Virgin Islands,"
		case .country_ag: return "Antigua and Barbuda"
		case .country_rs: return "Serbia"
		case .country_al: return "Albania"
		case .country_me: return "Montenegro"
		case .country_bs: return "Bahamas"
		case .country_ch: return "Switzerland"
		case .country_mp: return "Northern Mariana Islands"
		case .country_mm: return "Myanmar"
		case .country_sb: return "Solomon Islands"
		case .country_bd: return "Bangladesh"
		case .country_gi: return "Gibraltar"
		case .country_mo: return "Macao"
		case .country_fj: return "Fiji"
		case .country_mw: return "Malawi"
		case .country_sx: return "Sint Maarten (Dutch part)"
		case .country_so: return "Somalia"
		case .country_hk: return "Hong Kong"
		case .country_sa: return "Saudi Arabia"
		case .country_no: return "Norway"
		case .country_ni: return "Nicaragua"
		case .country_sg: return "Singapore"
		case .country_tr: return "Turkey"
		case .country_ax: return "Åland Islands"
		case .country_pg: return "Papua New Guinea"
		case .country_dm: return "Dominica"
		case .country_tt: return "Trinidad and Tobago"
		case .country_am: return "Armenia"
		case .country_dj: return "Djibouti"
		case .country_tv: return "Tuvalu"
		case .country_pt: return "Portugal"
		case .country_cu: return "Cuba"
		case .country_aq: return "Antarctica"
		case .country_gr: return "Greece"
		case .country_gw: return "Guinea-Bissau"
		case .country_wf: return "Wallis and Futuna"
		case .country_tc: return "Turks and Caicos Islands"
		case .country_sr: return "Suriname"
		case .country_gl: return "Greenland"
		case .country_aw: return "Aruba"
		case .country_lu: return "Luxembourg"
		case .country_ru: return "Russian Federation"
		case .country_kw: return "Kuwait"
		case .country_bl: return "Saint Barthélemy"
		case .country_bt: return "Bhutan"
		case .country_mz: return "Mozambique"
		case .country_pe: return "Peru"
		case .country_pn: return "Pitcairn"
		case .country_cv: return "Cabo Verde"
		case .country_sk: return "Slovakia"
		case .country_nu: return "Niue"
		case .country_at: return "Austria"
		case .country_it: return "Italy"
		case .country_az: return "Azerbaijan"
		case .country_uy: return "Uruguay"
		case .country_gu: return "Guam"
		case .country_sh: return "Saint Helena, Ascension and Tristan da Cunha"
		case .country_ht: return "Haiti"
		case .country_ph: return "Philippines"
		case .country_lb: return "Lebanon"
		case .country_va: return "Holy See"
		case .country_si: return "Slovenia"
		case .country_br: return "Brazil"
		case .country_mn: return "Mongolia"
		case .country_kr: return "Korea, Republic of"
		case .country_hr: return "Croatia"
		case .country_fi: return "Finland"
		case .country_ga: return "Gabon"
		case .country_lt: return "Lithuania"
		case .country_yt: return "Mayotte"
		case .country_lv: return "Latvia"
		case .country_ma: return "Morocco"
		case .country_kp: return "Korea, Democratic People''s Republic of"
		case .country_er: return "Eritrea"
		case .country_ps: return "Palestine, State of"
		case .country_pk: return "Pakistan"
		case .country_ly: return "Libya"
		case .country_pa: return "Panama"
		case .country_kz: return "Kazakhstan"
		case .country_hn: return "Honduras"
		case .country_as: return "American Samoa"
		case .country_fr: return "France"
		case .country_mr: return "Mauritania"
		case .country_mx: return "Mexico"
		case .country_sm: return "San Marino"
		case .country_cz: return "Czechia"
		case .country_nl: return "Netherlands"
		case .country_za: return "South Africa"
		case .country_ec: return "Ecuador"
		case .country_tw: return "Taiwan, Province of China"
		case .country_tl: return "Timor-Leste"
		case .country_mk: return "Macedonia, the former Yugoslav Republic of"
		case .country_fm: return "Micronesia, Federated States of"
		case .country_lc: return "Saint Lucia"
		case .country_la: return "Lao People''s Democratic Republic"
		case .country_ls: return "Lesotho"
		case .country_hu: return "Hungary"
		case .country_gh: return "Ghana"
		case .country_lk: return "Sri Lanka"
		case .country_tf: return "French Southern Territories"
		case .country_tk: return "Tokelau"
		case .country_pf: return "French Polynesia"
		case .country_ir: return "Iran, Islamic Republic of"
		case .country_li: return "Liechtenstein"
		case .country_bi: return "Burundi"
		case .country_gq: return "Equatorial Guinea"
		case .country_iq: return "Iraq"
		case .country_ml: return "Mali"
		case .country_ky: return "Cayman Islands"
		case .country_ss: return "South Sudan"
		case .country_tg: return "Togo"
		case .country_cd: return "Congo, the Democratic Republic of the"
		case .country_io: return "British Indian Ocean Territory"
		case .country_bn: return "Brunei Darussalam"
		case .country_gy: return "Guyana"
		case .country_bb: return "Barbados"
		case .country_ke: return "Kenya"
		case .country_nr: return "Nauru"
		case .country_sc: return "Seychelles"
		case .country_um: return "United States Minor Outlying Islands"
		case .country_et: return "Ethiopia"
		case .country_bv: return "Bouvet Island"
		case .country_fo: return "Faroe Islands"
		case .country_es: return "Spain"
		case .country_mq: return "Martinique"
		case .country_ai: return "Anguilla"
		case .country_nf: return "Norfolk Island"
		case .country_sd: return "Sudan"
		case .country_tn: return "Tunisia"
		case .country_in: return "India"
		case .country_st: return "Sao Tome and Principe"
		case .country_na: return "Namibia"
		case .country_cm: return "Cameroon"
		case .country_jm: return "Jamaica"
		case .country_ba: return "Bosnia and Herzegovina"
		case .country_sl: return "Sierra Leone"
		case .country_gd: return "Grenada"
		case .country_fk: return "Falkland Islands (Malvinas)"
		case .country_do: return "Dominican Republic"
		case .country_ci: return "Côte d''Ivoire"
		case .country_bh: return "Bahrain"
		case .country_dk: return "Denmark"
		case .country_kg: return "Kyrgyzstan"
		case .country_pm: return "Saint Pierre and Miquelon"
		case .country_mh: return "Marshall Islands"
		case .country_bf: return "Burkina Faso"
		case .country_pl: return "Poland"
		case .country_uz: return "Uzbekistan"
		case .country_gb: return "United Kingdom of Great Britain and Northern Ireland"
		case .country_bo: return "Bolivia, Plurinational State of"
		case .country_ar: return "Argentina"
		case .country_id: return "Indonesia"
		case .country_lr: return "Liberia"
		case .country_gs: return "South Georgia and the South Sandwich Islands"
		case .country_mu: return "Mauritius"
		case .country_ug: return "Uganda"
		case .country_kh: return "Cambodia"
		case .country_ro: return "Romania"
		case .country_ws: return "Samoa"
		case .country_vu: return "Vanuatu"
		case .country_bm: return "Bermuda"
		case .country_is: return "Iceland"
		case .country_vc: return "Saint Vincent and the Grenadines"
		case .country_gp: return "Guadeloupe"
		case .country_td: return "Chad"
		case .country_eg: return "Egypt"
		case .country_mg: return "Madagascar"
		case .country_md: return "Moldova, Republic of"
		case .country_vg: return "Virgin Islands, British"
		case .country_de: return "Germany"
		case .country_pr: return "Puerto Rico"
		case .country_ae: return "United Arab Emirates"
		case .country_jo: return "Jordan"
		case .country_cc: return "Cocos (Keeling) Islands"
		case .country_sv: return "El Salvador"
		case .country_sz: return "Swaziland"
		case .country_th: return "Thailand"
		case .country_ki: return "Kiribati"
		case .country_gg: return "Guernsey"
		case .country_nc: return "New Caledonia"
		case .country_au: return "Australia"
		case .country_ca: return "Canada"
		case .country_im: return "Isle of Man"
		case .country_tm: return "Turkmenistan"
		case .country_rw: return "Rwanda"
		case .country_bg: return "Bulgaria"
		case .country_cn: return "China"
		case .country_gt: return "Guatemala"
		case .country_py: return "Paraguay"
		case .country_vn: return "Viet Nam"
		case .country_co: return "Colombia"
		case .country_ee: return "Estonia"
		case .country_pw: return "Palau"
		case .country_re: return "Réunion"
		case .country_sj: return "Svalbard and Jan Mayen"
		case .country_ao: return "Angola"
		case .country_cf: return "Central African Republic"
		case .country_cg: return "Congo"
		case .country_nz: return "New Zealand"
		case .country_qa: return "Qatar"
		case .country_be: return "Belgium"
		case .country_us: return "United States of America"
		case .country_jp: return "Japan"
		case .country_mt: return "Malta"
		case .country_ge: return "Georgia"
		case .country_gf: return "French Guiana"
		case .country_km: return "Comoros"
		case .country_ng: return "Nigeria"
		case .country_se: return "Sweden"
		case .country_np: return "Nepal"
		case .country_kn: return "Saint Kitts and Nevis"
		case .country_il: return "Israel"
		case .country_bw: return "Botswana"
		case .country_cy: return "Cyprus"
		}
	}
}
