// Generated from https://github.com/ehn-dcc-development/ehn-dcc-schema => valuesets/test-manf.json
import Foundation
enum LabTestManufacturer: String {
	case unknown = "unknown"
	case manufacturer1218 = "1218"
	case manufacturer1437 = "1437"
	case manufacturer1253 = "1253"
	case manufacturer308 = "308"
	case manufacturer1490 = "1490"
	case manufacturer1604 = "1604"
	case manufacturer1844 = "1844"
	case manufacturer1769 = "1769"
	case manufacturer1295 = "1295"
	case manufacturer768 = "768"
	case manufacturer1232 = "1232"
	case manufacturer1456 = "1456"
	case manufacturer1215 = "1215"
	case manufacturer1934 = "1934"
	case manufacturer1267 = "1267"
	case manufacturer1466 = "1466"
	case manufacturer1097 = "1097"
	case manufacturer1763 = "1763"
	case manufacturer1173 = "1173"
	case manufacturer1815 = "1815"
	case manufacturer1392 = "1392"
	case manufacturer1375 = "1375"
	case manufacturer1144 = "1144"
	case manufacturer1271 = "1271"
	case manufacturer1199 = "1199"
	case manufacturer1822 = "1822"
	case manufacturer1489 = "1489"
	case manufacturer1162 = "1162"
	case manufacturer1484 = "1484"
	case manufacturer1341 = "1341"
	case manufacturer1363 = "1363"
	case manufacturer1833 = "1833"
	case manufacturer1654 = "1654"
	case manufacturer1884 = "1884"
	case manufacturer1278 = "1278"
	case manufacturer1365 = "1365"
	case manufacturer1747 = "1747"
	case manufacturer1266 = "1266"
	case manufacturer1296 = "1296"
	case manufacturer2010 = "2010"
	case manufacturer1870 = "1870"
	case manufacturer1190 = "1190"
	case manufacturer1331 = "1331"
	case manufacturer1764 = "1764"
	case manufacturer1236 = "1236"
	case manufacturer1481 = "1481"
	case manufacturer1223 = "1223"
	case manufacturer1343 = "1343"
	case manufacturer2017 = "2017"
	case manufacturer1180 = "1180"
	case manufacturer1268 = "1268"
	case manufacturer1919 = "1919"
	case manufacturer1246 = "1246"
	case manufacturer1333 = "1333"
	case manufacturer1304 = "1304"
	case manufacturer1443 = "1443"
	case manufacturer1767 = "1767"
	case manufacturer1360 = "1360"
	case manufacturer344 = "344"
	case manufacturer1906 = "1906"
	case manufacturer1420 = "1420"
	case manufacturer1225 = "1225"
	case manufacturer1263 = "1263"
	case manufacturer345 = "345"
	case manufacturer1319 = "1319"
	case manufacturer1244 = "1244"
	case manufacturer1606 = "1606"
	case manufacturer1256 = "1256"
	case manufacturer1468 = "1468"
	case manufacturer1114 = "1114"
	case manufacturer1574 = "1574"
	case manufacturer1736 = "1736"
	var display: String {
		switch self {
		case .unknown: return "unknown"
		case .manufacturer1218: return "Siemens Healthineers, CLINITEST Rapid Covid-19 Antigen Test"
		case .manufacturer1437: return "Guangzhou Wondfo Biotech Co., Ltd, Wondfo 2019-nCoV Antigen Test (Lateral Flow Method)"
		case .manufacturer1253: return "GenSure Biotech Inc, GenSure COVID-19 Antigen Rapid Kit (REF: P2004)"
		case .manufacturer308: return "PCL Inc, PCL COVID19 Ag Rapid FIA"
		case .manufacturer1490: return "Safecare Biotech (Hangzhou) Co. Ltd, Multi-Respiratory Virus Antigen Test Kit(Swab)  (Influenza A+B/ COVID-19)"
		case .manufacturer1604: return "Roche (SD BIOSENSOR), SARS-CoV-2 Antigen Rapid Test"
		case .manufacturer1844: return "Hangzhou Immuno Biotech Co.,Ltd, Immunobio SARS-CoV-2 Antigen ANTERIOR NASAL Rapid Test Kit (minimal invasive)"
		case .manufacturer1769: return "Shenzhen Watmind Medical Co., Ltd, SARS-CoV-2 Ag Diagnostic Test Kit (Colloidal Gold)"
		case .manufacturer1295: return "Zhejiang Anji Saianfu Biotech Co., Ltd, reOpenTest COVID-19 Antigen Rapid Test"
		case .manufacturer768: return "ArcDia International Ltd, mariPOC SARS-CoV-2"
		case .manufacturer1232: return "Abbott Rapid Diagnostics, Panbio COVID-19 Ag Rapid Test"
		case .manufacturer1456: return "Xiamen Wiz Biotech Co., Ltd, SARS-CoV-2 Antigen Rapid Test"
		case .manufacturer1215: return "Hangzhou Laihe Biotech Co., Ltd, LYHER Novel Coronavirus (COVID-19) Antigen Test Kit(Colloidal Gold)"
		case .manufacturer1934: return "Tody Laboratories Int., Coronavirus (SARS-CoV 2) Antigen - Oral Fluid"
		case .manufacturer1267: return "LumiQuick Diagnostics Inc, QuickProfile COVID-19 Antigen Test"
		case .manufacturer1466: return "TODA PHARMA, TODA CORONADIAG Ag"
		case .manufacturer1097: return "Quidel Corporation, Sofia SARS Antigen FIA"
		case .manufacturer1763: return "Xiamen AmonMed Biotechnology Co., Ltd, COVID-19 Antigen Rapid Test Kit (Colloidal Gold)"
		case .manufacturer1173: return "CerTest Biotec, CerTest SARS-CoV-2 Card test"
		case .manufacturer1815: return "Anhui Deep Blue Medical Technology Co., Ltd, COVID-19 (SARS-CoV-2) Antigen Test Kit (Colloidal Gold) - Nasal Swab"
		case .manufacturer1392: return "Hangzhou Testsea Biotechnology Co., Ltd, COVID-19 Antigen Test Cassette"
		case .manufacturer1375: return "DIALAB GmbH, DIAQUICK COVID-19 Ag Cassette"
		case .manufacturer1144: return "Green Cross Medical Science Corp., GENEDIA W COVID-19 Ag"
		case .manufacturer1271: return "Precision Biosensor, Inc, Exdia COVID-19 Ag"
		case .manufacturer1199: return "Oncosem Onkolojik Sistemler San. ve Tic. A.S., CAT"
		case .manufacturer1822: return "Anbio (Xiamen) Biotechnology Co., Ltd, Rapid COVID-19 Antigen Test(Colloidal Gold)"
		case .manufacturer1489: return "Safecare Biotech (Hangzhou) Co. Ltd, COVID-19 Antigen Rapid Test Kit (Swab)"
		case .manufacturer1162: return "Nal von minden GmbH, NADAL COVID-19 Ag Test"
		case .manufacturer1484: return "Beijing Wantai Biological Pharmacy Enterprise Co., Ltd, Wantai SARS-CoV-2 Ag Rapid Test (FIA)"
		case .manufacturer1341: return "Qingdao Hightop Biotech Co., Ltd, SARS-CoV-2 Antigen Rapid Test (Immunochromatography)"
		case .manufacturer1363: return "Hangzhou Clongene Biotech Co., Ltd, Covid-19 Antigen Rapid Test Kit"
		case .manufacturer1833: return "AAZ-LMB, COVID-VIRO"
		case .manufacturer1654: return "Asan Pharmaceutical CO., LTD, Asan Easy Test COVID-19 Ag"
		case .manufacturer1884: return "Xiamen Wiz Biotech Co., Ltd, SARS-CoV-2 Antigen Rapid Test (Colloidal Gold)"
		case .manufacturer1278: return "Xiamen Boson Biotech Co. Ltd, Rapid SARS-CoV-2 Antigen Test Card"
		case .manufacturer1365: return "Hangzhou Clongene Biotech Co., Ltd, COVID-19/Influenza A+B Antigen Combo Rapid Test"
		case .manufacturer1747: return "Guangdong Hecin Scientific, Inc., 2019-nCoV Antigen Test Kit (colloidal gold method)"
		case .manufacturer1266: return "Labnovation Technologies Inc, SARS-CoV-2 Antigen Rapid Test Kit"
		case .manufacturer1296: return "Zhejiang Anji Saianfu Biotech Co., Ltd, AndLucky COVID-19 Antigen Rapid Test"
		case .manufacturer2010: return "Atlas Link Technology Co., Ltd., NOVA Test® SARS-CoV-2 Antigen Rapid Test Kit (Colloidal Gold Immunochromatography)"
		case .manufacturer1870: return "Beijing Hotgen Biotech Co., Ltd, Novel Coronavirus 2019-nCoV Antigen Test (Colloidal Gold)"
		case .manufacturer1190: return "möLab, COVID-19 Rapid Antigen Test"
		case .manufacturer1331: return "Beijing Lepu Medical Technology Co., Ltd, SARS-CoV-2 Antigen Rapid Test Kit"
		case .manufacturer1764: return "JOYSBIO (Tianjin) Biotechnology Co., Ltd, SARS-CoV-2 Antigen Rapid Test Kit (Colloidal Gold)"
		case .manufacturer1236: return "BTNX Inc, Rapid Response COVID-19 Antigen Rapid Test"
		case .manufacturer1481: return "MP Biomedicals, Rapid SARS-CoV-2 Antigen Test Card"
		case .manufacturer1223: return "BIOSYNEX S.A., BIOSYNEX COVID-19 Ag BSS"
		case .manufacturer1343: return "Zhezhiang Orient Gene Biotech Co., Ltd, Coronavirus Ag Rapid Test Cassette (Swab)"
		case .manufacturer2017: return "Shenzhen Ultra-Diagnostics Biotec.Co.,Ltd, SARS-CoV-2 Antigen Test Kit"
		case .manufacturer1180: return "MEDsan GmbH, MEDsan SARS-CoV-2 Antigen Rapid Test"
		case .manufacturer1268: return "LumiraDX, LumiraDx SARS-CoV-2 Ag Test"
		case .manufacturer1919: return "Core Technology Co., Ltd, Coretests COVID-19 Ag Test"
		case .manufacturer1246: return "VivaChek Biotech (Hangzhou) Co., Ltd, Vivadiag SARS CoV 2 Ag Rapid Test"
		case .manufacturer1333: return "Joinstar Biomedical Technology Co., Ltd, COVID-19 Rapid Antigen Test (Colloidal Gold)"
		case .manufacturer1304: return "AMEDA Labordiagnostik GmbH, AMP Rapid Test SARS-CoV-2 Ag"
		case .manufacturer1443: return "Vitrosens Biotechnology Co., Ltd, RapidFor SARS-CoV-2 Rapid Ag Test"
		case .manufacturer1767: return "Healgen Scientific, Coronavirus Ag Rapid Test Cassette"
		case .manufacturer1360: return "Guangdong Wesail Biotech Co., Ltd, COVID-19 Ag Test Kit"
		case .manufacturer344: return "SD BIOSENSOR Inc, STANDARD F COVID-19 Ag FIA"
		case .manufacturer1906: return "Azure Biotech Inc, COVID-19 Antigen Rapid Test Device"
		case .manufacturer1420: return "NanoEntek, FREND COVID-19 Ag"
		case .manufacturer1225: return "DDS DIAGNOSTIC, Test Rapid Covid-19 Antigen (tampon nazofaringian)"
		case .manufacturer1263: return "Humasis, Humasis COVID-19 Ag Test"
		case .manufacturer345: return "SD BIOSENSOR Inc, STANDARD Q COVID-19 Ag Test"
		case .manufacturer1319: return "SGA Medikal, V-Chek SARS-CoV-2 Ag Rapid Test Kit (Colloidal Gold)"
		case .manufacturer1244: return "GenBody, Inc, Genbody COVID-19 Ag Test"
		case .manufacturer1606: return "RapiGEN Inc, BIOCREDIT COVID-19 Ag - SARS-CoV 2 Antigen test"
		case .manufacturer1256: return "Hangzhou AllTest Biotech Co., Ltd, COVID-19 and Influenza A+B Antigen Combo Rapid Test"
		case .manufacturer1468: return "ACON Laboratories, Inc, Flowflex SARS-CoV-2 Antigen rapid test"
		case .manufacturer1114: return "Sugentech, Inc, SGTi-flex COVID-19 Ag"
		case .manufacturer1574: return "Shenzhen Zhenrui Biotechnology Co., Ltd, Zhenrui ®COVID-19 Antigen Test Cassette"
		case .manufacturer1736: return "Anhui Deep Blue Medical Technology Co., Ltd, COVID-19 (SARS-CoV-2) Antigen Test Kit(Colloidal Gold)"
		}
	}
}
